const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUhFQVhlYnByQmJQeTlQNmZaUXpjMlkyM3F2VlpoMGNDWlc3Y1EzSXMzWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRStRNWljNGVMME9hTUorZ1kwV3BWWHdXRUxDVlB2bC95M21LWVFZNjRnbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBQnlyQ0JoSlVidFlFMEMzSXIvQzFnV0dodVNuR0lvdTdScE10cmlXWUVvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3L0ZFSU1kZ2hEbnpBRGVEUTM5OXJJSmplZStFYUk3YkZVNmkvRlZkdGljPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNMcDRReVN1aGlzMUVUUk9KaDlqMVlKRkJzSVFTVm50M2UvOWdPUlk1bms9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjQwWmEzQjR2UE1uc1l2ejFuWnhhcVJkMm45SWdFMXJrQ3MrTnJOV3p5VlU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkx5eUNMKzlmSHpHZGRaeXpzWWd2NlBIRmpTY2lha0UyZ1grZjhEMW1VND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSGh5SVVDUVREYUpyVXgrcERBU1g5cWNzUDFYZUZFV1FtODhncm1zQTFCMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IiszYXVxNFBHQ09LWTlUd2hhVjhGc0xmR0FlekZjL0xYSlVLSThpMmF0SmNUcEs5c0ZHMHE5eGxYV2E1QUZmQk9LNDFpcW5SUnhmK1FZNk8vMVNDNERnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTgsImFkdlNlY3JldEtleSI6InFXQy94ekxxbHk4NDZXVTltYlZ1dGIyUVhHUWF6U0Q4L2hXQTZKcmkzUzg9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6Ijk0dHdhcHZyUmpTTC05VUh2emkwYmciLCJwaG9uZUlkIjoiYjkwZjg1OTctMTQwZS00MTgyLWI5NjUtNGJlZWY2N2Y0MWI3IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im12L1NrcHBCVnB6TkoxSDhmZ0JBOERkdDdXOD0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJMRDRiZEQ2enFodFlGaWM0WW9WZW02Z3J0NjA9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiWjRIR1Y1WkMiLCJtZSI6eyJpZCI6IjI1NjcwMDI0NzQ3MDozNUBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJLSEFSRUwifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ043NHJiZ0NFSWpOM0xzR0dBY2dBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImVaQkJNWXM4N2hLNGhyVHVvWWt2bWp0YlR6WE5LMjl4VTZ2aGwzS3dFMG89IiwiYWNjb3VudFNpZ25hdHVyZSI6IjJqMlBHejFzNlBTQ0xHSlB1aEIzV3VySHVRTVRJaTg0SHNrN3REUE8zK1NrUnVmNGlDYmRpVVl3eDRYbytzcDJVU0xEaW0wVWRjbDdJcm14TVpRQkJBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJBSHlCc0phcVpCSy9TR0JJWGd2SzlpcVBuNkZVRXhGK0VmenVFdXJwMnF0ZEtKcHpvL1JxME9uVm1xTWdZNXFJczVsUUwyQkZHejQ5TUwvK3RJbUVDdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NjcwMDI0NzQ3MDozNUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJYbVFRVEdMUE80U3VJYTA3cUdKTDVvN1cwODF6U3R2Y1ZPcjRaZHlzQk5LIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM1ODYxOTEwLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUhMYSJ9",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "256700247470",
  "OWNER_NAME": process.env.OWNER_NAME || "Kharel",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "typing",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
