const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNlAvWVd2Z1dNQkFYL3d4RUw5Sm0ybjdkZU1vc0VnZ0MrRUxwTEplNFgxVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNE1kOExWbkg4RXBwbmJFbmJOZjdjSFBMSmFEV1pGSDJiVTgrSlRFUGtuOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ3THlvdnJDUWtUaGZVZ0JQL1hydk9wTkd2WlA4b3Bnd041UzZKNS9xUW5nPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLZ3E5cnBMNjgxdHJ5MUtYaUMwSlFwTVlZdGpvSnVqSEQ0NXhBUHViU2pjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndFNzNlNnNxWGp3M2t2STBhVGJGUUVJVkpOdUJPL0F3YWlXSVQyWCt0bDg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikx2TXVWTjB4NXJWQXdYOUhndElWMFJsclJ4UHh5UFFEZGtBMkVJcjFJamM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY1B3QldQQnlMRFEvOVBWcko3TXFXdHEvejZNUmRaK3h0UU5nZTl5UHMxbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRjZxRE9CakRvYnM3OWYydFB5dlhmTUJvVS8rbUFrVlNHcEdqekZmdHdrND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImhzTkFwNFpFUkNIYzI3L1FIdVNsZmRCZ0hoQmtMalVNZUFLZ2hXK3ZmakVYYUZpUXRNendvT01odGkrb2tacnpaaUc3UHNiTW5od1JCNDlFb2VQVkFBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjM4LCJhZHZTZWNyZXRLZXkiOiJZa2duSmNIektVMXFvZnZrNVUwaHN0NzluN3d2NFlxczV1MXlySlBWV0FRPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJZaWpDbnFaUVIxQzFZQjlaZDJvdVhBIiwicGhvbmVJZCI6ImYxZTVjNGIwLWRkNTAtNDRhNy05YmU1LTg4ODBjNTMzZjkxMSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJsZE50R21aRkUySjdoYWNQTXF0VzMxdlA0NjQ9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicllCVWJHV3dKaVlFNWVrbXJJNW9LdDZLSmxvPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkdISlFRWFpTIiwibWUiOnsiaWQiOiIyNDEwNzE2NDczMjo0QHMud2hhdHNhcHAubmV0In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNLS0t0VFlRbkw3YXV3WVlBU0FBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJpZHdzNDhSaDFjZnFmU1djSFNNc2ZwUStLWmxsK3RRVCtydFZ3SmhUZ0VrPSIsImFjY291bnRTaWduYXR1cmUiOiJOZUNOb3JwQWlONDNCM1JrRG9DdEpmSm9UQ0lBSUE3Q3QwMmhKTEsrb1QwUGZFV3pHVmhYVmNIWndxYis1U1hhTGMzNG4raUpSZXlqRVJuLzBjNWZEUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiTndtK3ljQnhoN0tHOG8xdm9saGlrL1BPODVWN2ZBbWx2V09pWS9ldTNrenpXcE5xcDVwdVNqb0crMy9SRjZFeWdINkZBMmtocENIU21maGJFMTFXQXc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNDEwNzE2NDczMjo0QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlluY0xPUEVZZFhINm4wbG5CMGpMSDZVUGltWlpmclVFL3E3VmNDWVU0QkoifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzU4MjcyNDEsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBS1E3In0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
